---
title: "HW7"
author: "Avinash Ramu"
date: "October 30, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q16.3


```{r q1_1}
#Use Andrew Stone's code from HW3 to ensure similar pre-processing
library(lme4)
library(arm)
library(rjags); library(R2jags)

# Loading HIV data
hiv.data <- read.csv("allvar.csv", header=TRUE)
# Square root transformation of the CD4PCT
hiv.data$rootCD4 <- sqrt(hiv.data$CD4PCT)
# Creation of time variable
hiv.data$time <- hiv.data$visage - hiv.data$baseage
# Removing those cases that have NAs for the DV or the time variable
data.noNA.CD4 <- hiv.data[complete.cases(hiv.data[,4]),]
data.noNA.CD4 <- data.noNA.CD4[complete.cases(data.noNA.CD4[,11]),]
# Creating indicators for each of the children
inddummies <- as.factor(data.noNA.CD4$newpid)
```

```{r q1_2}
mlm.1 <- lmer(rootCD4 ~ time + (1 | inddummies), data=data.noNA.CD4)
display(mlm.1)

n <- nrow(data.noNA.CD4)
y <- data.noNA.CD4$rootCD4
time <- data.noNA.CD4$time

# get ind index variable
ui <- unique(inddummies)
J <- length(ui)
ind <- rep (NA, J)
for (i in 1:J) {
  ind[inddummies == ui[i]] <- i
}


the.model <- "model{
  for (i in 1:n){
    y[i] ~ dnorm (y.hat[i], tau.y)
    y.hat[i] <- a[ind[i]] + b * time[i]
  }
  b ~ dnorm (0, .0001)
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif (0, 100)
  
  for (j in 1:J){
    a[j] ~ dnorm (mu.a, tau.a)
  }
  mu.a ~ dnorm (0, .0001)
  tau.a <- pow(sigma.a, -2)
  sigma.a ~ dunif (0, 100)
}"
data <- list ("n", "J", "y", "time", "ind")
# Defining the initial values that your model's parameters (values you *don't* already know)
inits <- function (){list(a=rnorm(J), 
                                b=rnorm(1), 
                                sigma.y=runif(1), 
                                sigma.a=runif(1))}
# Defining which parameters of your model you want JAGS to return to you 
# In the book (page 366), they are missing "g.0" and "g.1"
parameters <- c ("a", "b", "sigma.y", "sigma.a")
# Now, we can actually run the model with the jags() function
m1 <- jags(data=data, 
                inits=inits, 
                parameters.to.save=parameters, 
                model.file=textConnection(the.model), # Note the textConnection() function
                n.chains=3, 
                n.iter=5000, 
                DIC=F)
m1
```


###PartB
```{r q1_3}
treatment <- data.noNA.CD4$treatmnt
baseage <- data.noNA.CD4$baseage
the.model2 <- "model{
  for (i in 1:n){
    y[i] ~ dnorm (y.hat[i], tau.y)
    y.hat[i] <- a[ind[i]] + b1 * time[i] + b2 * treatment[i] + b3 * baseage[i]
  }
  b1 ~ dnorm (0, .0001)
  b2 ~ dnorm (0, .0001)
  b3 ~ dnorm (0, .0001)
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif (0, 100)
  
  for (j in 1:J){
    a[j] ~ dnorm (mu.a, tau.a)
  }
  mu.a ~ dnorm (0, .0001)
  tau.a <- pow(sigma.a, -2)
  sigma.a ~ dunif (0, 100)
}"
data <- list ("n", "J", "y", "time", "ind", "treatment", "baseage")
inits <- function (){list(a=rnorm(J), 
                                b1 = rnorm(1),
                                b2 = rnorm(1),
                                b3 = rnorm(1),
                                sigma.y=runif(1), 
                                sigma.a=runif(1))}
parameters <- c ("a", "b1", "b2", "b3", "sigma.y", "sigma.a")
m2 <- jags(data=data, 
                inits=inits, 
                parameters.to.save=parameters, 
                model.file=textConnection(the.model2), # Note the textConnection() function
                n.chains=3, 
                n.iter=5000, 
                DIC=F)
m2
```

## Q16.8


```{r q2_1}
##Use Andy's tutorial code

```


## Rerun Q16.3 using 17.2 and 17.3
###Use varying slopes on model fit in 16.3(B)

I used a varying slope on the time variable here.
There are fixed slopes for treatment, time and age as in the model in 12.2(B).
There is a varying intercept term as well.
```{r q3_1}
y <- data.noNA.CD4$rootCD4
time <- data.noNA.CD4$time
treatment <- data.noNA.CD4$treatmnt
baseage <- data.noNA.CD4$baseage
inddummies <- as.factor(data.noNA.CD4$newpid)
n <- nrow(data.noNA.CD4)
# get ind index variable
ui <- unique(inddummies)
J <- length(ui)
ind <- rep (NA, J)
for (i in 1:J) {
  ind[inddummies == ui[i]] <- i
}
the.model3 <- "model{
  for (i in 1:n){
    y[i] ~ dnorm (y.hat[i], tau.y)
    y.hat[i] <- a[ind[i]] + b1 * time[i] + b2 * treatment[i] + b3 * baseage[i] + b4[ind[i]] * time[i]
  }
  b1 ~ dnorm (0, .0001)
  b2 ~ dnorm (0, .0001)
  b3 ~ dnorm (0, .0001)
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif (0, 100)
  for (j in 1:J){
    a[j] ~ dnorm (a.hat[j], tau.a)
    b4[j] ~ dnorm (b.hat4[j], tau.b4)
    a.hat[j] <- mu.a
    b.hat4[j] <- mu.b4
  }
  mu.a ~ dnorm (0, .0001)
  tau.a <- pow(sigma.a, -2)
  sigma.a ~ dunif (0, 100)
  mu.b4 ~ dnorm (0, .0001)
  tau.b4 <- pow(sigma.b4, -2)
  sigma.b4 ~ dunif (0, 100)
}"
data <- list ("n", "J", "y", "time", "ind", "treatment", "baseage")
inits <- function (){list(a=rnorm(J), 
                                b1 = rnorm(1),
                                b2 = rnorm(1),
                                b3 = rnorm(1),
                                b4 = rnorm(J),
                                sigma.y=runif(1), 
                                sigma.a=runif(1),
                                sigma.b4 = runif(1))}
parameters <- c ("a", "b1", "b2", "b3", "b4", "sigma.y", "sigma.a")
m3 <- jags(data=data, 
                inits=inits, 
                parameters.to.save=parameters, 
                model.file=textConnection(the.model3), # Note the textConnection() function
                n.chains=3, 
                n.iter=5000, 
                DIC=F)
m3
```

## Q17.5

```{r q4_1}
##From Andrew Stone's HW4 solution
age.data <- read.csv("age.guessing.csv")
# Empty matrix to put observations into
analysis.matrix <- matrix(NA, nrow=100, ncol=3)
ages <- c()
group <- c()
person <- rep(c(1:10), times=10) # Creating individual ID variable
# For loop creates the (non-abs value) dependent variable and the group ID variable
for(i in 1:10){
ages <- c(ages, as.integer(age.data[i,3:12]))
group <- c(group, rep(age.data[i,1], times=10))
}
# Adding the variables to the matrix
analysis.matrix[,1] <- ages
analysis.matrix[,2] <- group
analysis.matrix[,3] <- person
# Turning the matrix into a data frame
model.data <- data.frame(analysis.matrix)
# Giving the variables in the data frame names
colnames(model.data) <- c("error", "group.id", "person.id")
# Turning the group and individual ID variables into factors
model.data$group.id <- as.factor(model.data$group.id)
model.data$person.id <- as.factor(model.data$person.id)
# Making the true DV by taking the absolute value
model.data$error <- abs(model.data$error)
# Multilevel model with separate coefficinets for each group and individual
age.model <- lmer(error ~ 1 + (1 | group.id) + (1 | person.id), data=model.data)
summary(age.model)
```

```{r q4_2}
n <- nrow(model.data)
y <- model.data$error
group.id <- model.data$group.id
person.id <- model.data$person.id
up <- unique(person.id)
J1 <- length(up)
person <- rep (NA, J1)
for (i in 1:J1) {
  person[person.id == up[i]] <- i
}
ug <- unique(group.id)
J2 <- length(ug)
group <- rep (NA, J2)
for (i in 1:J2) {
  group[group.id == ug[i]] <- i
}

the.model4 <- "model{
  for (i in 1:n){
    y[i] ~ dnorm (y.hat[i], tau.y)
    y.hat[i] <- a + b[person[i]] + c[group[i]]
  }
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif (0, 100)
  for (j in 1:J1){
    b[j] ~ dnorm (mu.b, tau.b[j])
    tau.b[j] <- pow(sigma.b[j], -2)
    sigma.b[j] ~ dunif (0, 100)
  }
  for (j in 1:J2){
    c[j] ~ dnorm (mu.c, tau.c[j])
    tau.c[j] <- pow(sigma.c[j], -2)
    sigma.c[j] ~ dunif (0, 100)
  }
  a ~ dnorm (mu.a, tau.a)
  mu.a ~ dnorm (0, .0001)
  mu.b ~ dnorm (0, .0001)
  mu.c ~ dnorm (0, .0001)
  tau.a <- pow(sigma.a, -2)
  sigma.a ~ dunif (0, 100)
}"
data <- list ("n", "J1", "J2", "y", "person", "group")
inits <- function (){list(a = rnorm(1), 
                                b = rnorm(J1),
                                c = rnorm(J2),
                                sigma.y = runif(1),
                                sigma.a = runif(1),
                                sigma.b = runif(J1),
                                sigma.c = runif(J2))}
parameters <- c ("a", "b", "c", "sigma.y", "sigma.a", "sigma.b", "sigma.c")
m4 <- jags(data=data, 
                inits=inits, 
                parameters.to.save=parameters, 
                model.file=textConnection(the.model4), # Note the textConnection() function
                n.chains=3, 
                n.iter=5000, 
                DIC=F)
m4
```
