---
title: "HW8"
author: "Avinash Ramu"
date: "November 9, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Q18.2
I will use the radon model that Andrew used in his demo.
```{r q2_1}
library(lme4)
library(arm)
library(rjags); library(R2jags)

# Setting up the data (from Gelman & Hill's website)
srrs2 <- read.table ("srrs2.dat", header=T, sep=",")
mn <- srrs2$state=="MN"
radon <- srrs2$activity[mn]
log.radon <- log (ifelse (radon==0, .1, radon))
floor <- srrs2$floor[mn]       # 0 for basement, 1 for first floor
n <- length(radon)
y <- log.radon
x <- floor

# get county index variable
county.name <- as.vector(srrs2$county[mn])
uniq <- unique(county.name)
J <- length(uniq)
county <- rep (NA, J)
for (i in 1:J){
  county[county.name==uniq[i]] <- i
}

srrs2.fips <- srrs2$stfips*1000 + srrs2$cntyfips
cty <- read.table ("cty.dat", header=T, sep=",")
usa.fips <- 1000*cty[,"stfips"] + cty[,"ctfips"]
usa.rows <- match (unique(srrs2.fips[mn]), usa.fips)
uranium <- cty[usa.rows,"Uppm"]
u <- log (uranium)

### The actual JAGS code begins here ###

# Saving the model to an object. This allows us to avoid saving the model to a .bug file and sourcing it in
# Make sure it is within quotations!
the.model <- "model{
  for (i in 1:n){
    y[i] ~ dnorm (y.hat[i], tau.y)
    y.hat[i] <- a[county[i]] + b*x[i]
  }
  b ~ dnorm (0, .0001)
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif (0, 100)
  
  for (j in 1:J){
    a[j] ~ dnorm (a.hat[j], tau.a)
    a.hat[j] <- g.0 + g.1*u[j]
  }
  g.0 ~ dnorm (0, .0001)
  g.1 ~ dnorm (0, .0001)
  tau.a <- pow(sigma.a, -2)
  sigma.a ~ dunif (0, 100)
}"

# Defining the data you will pass into the model -- you *already know* these values
radon.data <- list ("n", "J", "x", "y", "county", "u")

# Defining the initial values that your model's parameters (values you *don't* already know)
radon.inits <- function (){list(a=rnorm(J), 
                                b=rnorm(1), 
                                g.0=rnorm(1), 
                                g.1=rnorm(1),
                                sigma.y=runif(1), 
                                sigma.a=runif(1))}

# Defining which parameters of your model you want JAGS to return to you 
# In the book (page 366), they are missing "g.0" and "g.1"
radon.parameters <- c ("a", "b", "sigma.y", "sigma.a", "g.0", "g.1")

# Now, we can actually run the model with the jags() function
radon.3 <- jags(data=radon.data, 
                inits=radon.inits, 
                parameters.to.save=radon.parameters, 
                model.file=textConnection(the.model), # Note the textConnection() function
                n.chains=3, 
                n.iter=5000, 
                DIC=F)

unpooled_model <- lm(y ~ floor + factor(county) - 1)


par(mfrow=c(3, 4))
counties <- sample(1:85, 4)
for(i in counties) {
  curve(dnorm(x, coef(unpooled_model)[i+1], se.coef(unpooled_model)[i+1]), main = uniq[i], ylab="", xlim=c(-5,5))
}

sigma.1 <- runif(1)
for(i in counties){
  curve(dnorm(x, radon.3[[2]]$mean$g.0 + radon.3[[2]]$mean$g.1 * uranium[i], sigma.1), from = -0.5, to = 4.5, main="Prior", xlim=c(-5,5))
}

for(i in counties){
  curve(dnorm(x, radon.3[[2]]$mean$a[i], radon.3[[2]]$sd$a[i]), from=-0.5, to=4.5, main="Posterior", ylab="", xlim=c(-5,5))
}

```


##Q18.4
### Part A
I have written this out on paper.


### Part B
```{r q3_1}
beauty <- read.csv("ProfEvaltnsBeautyPublic.csv")
attach(beauty)
C <- 3
censored <- courseevaluation < 3
censored_eval <- ifelse(censored, C, courseevaluation)
Loglik <- function (parameter.vector, x, y, C) {
  a <- parameter.vector[1]
  b <- parameter.vector[2]
  sigma <- parameter.vector[3]
  ll.vec <- ifelse (y<C, dnorm (y, a + b*x, sigma, log=TRUE),
  pnorm ((a + b*x - C)/sigma, log=TRUE))
  return (sum (ll.vec))
}
inits <- runif (3)
mle <- optim (inits, Loglik, lower=c(-Inf,-Inf,1.e-5), method="L-BFGS-B", control=list(fnscale=-1), x = btystdave, y = censored_eval, C=200)
mle$par
```


### Part C
```{r q3_3}
beauty <- read.csv("ProfEvaltnsBeautyPublic.csv")
attach(beauty)
model1 <- "model { 
  for (i in 1:n){
    isCensored[i] ~ dinterval(y[i], censorLimitVec)
    y[i] ~ dnorm(yhat[i], tau.y)
    yhat[i] <- a + b*x[i]
  }
  a ~ dnorm(0, 1E-6)
  b ~ dnorm(0, 1E-6)
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif (0, 100)
}"
C <- 3
N <- length(courseevaluation)
censored <- courseevaluation < 3
y1 <- ifelse (censored, NA, courseevaluation)
censorLimitVec = 3
beauty_data <- list (x = btystdave, y = y1, n = N, isCensored = as.numeric(censored), censorLimitVec = censorLimitVec)
beauty_inits <- function() { list(a=rnorm(1), b=rnorm(1), sigma.y=runif(1)) }
params <- c ("a", "b", "sigma.y")
radon.3 <- jags(data = beauty_data, 
                inits = beauty_inits, 
                parameters.to.save = params, 
                model.file = textConnection(model1), # Note the textConnection() function
                n.chains = 3, 
                n.iter = 5000, 
                DIC = F)
radon.3
```

### Part D
Regression without censoring
```{r q3_4}
unpooled_model <- lm(courseevaluation ~ btystdave)
unpooled_model
```